version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saaspms
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    networks:
      - local_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/saaspms?schema=public
      - NEXTAUTH_SECRET=super_secret_for_local_dev_only
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
    networks:
      - local_network

volumes:
  pgdata_local:

networks:
  local_network:
